linters:
  enable:
    - asciicheck
    - godot
    - cyclop
    - gomnd
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - unparam
    - govet
    - bodyclose
    - errname
    - gofmt
    - goimports
    - revive

linters-settings:
  cyclop:
    max-complexity: 20

issues:
  exclude-files:
    - pkg/domain/hexutil.go
