version: '3.9'

services:
  parser:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    container_name: parser-app
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./:/app
