version: '3.9'

services:
  parser:
    build:
      dockerfile: Dockerfile.dev
    container_name: parser-app-test
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./:/app
